name: Continuous-delivery

# Controls when the workflow will run
on:
  # Triggers the workflow
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install 🔧
        run: npm install

      - name: Build ⛏️
        run: |
          npm run docs:build
          node ./scripts/spa-gh-pages.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs-dist # The folder the action should deploy.


      # - name: Update block Json 🪓
      #   run: npm run update-block
